### ISSUE TITLE
Configurar classe Funcionário

### ISSUE THREAD

**Issue by RodgerOliver** [RodgerOliver/gerenciador-de-empresa#11]
# Todo
- [x] Criar construtor com todos os atributos
- [x] Criar método "consultaMedica" que retorna o preço comum da consulta com desconto de 50% caso ele tenha beneficio médico
  - [x] Adicionar parâmetro ao método "double valorConsulta"
  - [x] Mudar retorno do método para double
- [x] Criar método "calculaINSS" que retorna o valor do INSS baseado no salário
- [x] Criar método "calculaSalario" onde retorna o sálario do funcionário menos o valor do INSS
  - [x] Mudar retorno do método para double
- [x] Renomear método "renomearContrato" para "toggleContrato"
- [x] Criar método "toggleContrato" que da toggle no atributo "ativo" e reseta seu salário para R$ 0,0
- [x] Mudar todos os atributos da classe para private
- [x] Transformar de classe abstrata para classe comum
- [x] Atualizar o README e o diagrama UML com a alteração acima
