### ISSUE TITLE
Configurar classe EmpresaSetorPrimario

### ISSUE THREAD

**Issue by RodgerOliver** [RodgerOliver/gerenciador-de-empresa#7]
# Todo
- [x] Criar construtor com todos os atributos
- [x] Sobreescrever método `dados` que retornar os dados do endereço
- [x] Sobreescrever método `produzir` que deve retornor a frase abaixo
  - "A empresa [nome] está transformando [materiaPrima] em [produtoFinal]"
