### ISSUE TITLE
Configurar classe EmpresaSetorTerciario

### ISSUE THREAD

**Issue by RodgerOliver** [RodgerOliver/gerenciador-de-empresa#9]
# Todo
- [x] Criar construtor com todos os atributos
- [x] Sobreescrever método `dados` que retornar os dados do endereço
- [x] Sobreescrever método `produzir` que deve retornor a frase abaixo
  - "A empresa [nome] presta o seguinte serviço: [servicoPrestado]"
